import { Prisma } from "@prisma/client";
import { ContactStatus, Priority } from "./contact";

export type PrismaContact = {
  id: string;
  name: string;
  email: string;
  phone: string | null;
  company: string | null;
  position: string | null;
  message: string;
  projectType: string | null;
  projectScope: string | null;
  budget: Prisma.Decimal | null;
  deadline: Date | null;
  existingSite: string | null;
  status: ContactStatus;
  priority: Priority;
  tags: Prisma.JsonValue;
  targetAudience: string | null;
  competitors: Prisma.JsonValue;
  objectives: Prisma.JsonValue;
  clientType: string | null;
  industry: string | null;
  companySize: string | null;
  annualRevenue: Prisma.Decimal | null;
  preferredContactMethod: string | null;
  marketingSource: string | null;
  newsletter: boolean;
  lastContact: Date | null;
  nextFollowUp: Date | null;
  notes: string | null;
  assignedTo: string | null;
  attachments: Prisma.JsonValue;
  quotationAmount: Prisma.Decimal | null;
  contractValue: Prisma.Decimal | null;
  ipAddress: string | null;
  userAgent: string | null;
  locale: string | null;
  timezone: string | null;
  createdAt: Date;
  updatedAt: Date;
};

export type ContactCreateInput = Prisma.ContactCreateInput;
export type ContactUpdateInput = Prisma.ContactUpdateInput;
